services:
  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth_dev
      POSTGRES_PASSWORD: "auth_dev#1234"
      POSTGRES_DB: auth_db_dev
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_dev -d auth_db_dev"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  auth_pgdata:
